
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 47323
	#The name of the modpack
	modpackName = "Extetho+"
	#The version of the modpack
	modpackVersion = "v2.0.3"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

